import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "../../components/ReactQueryClientProvider";
import { Suspense } from 'react'
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Suspense>
    <ReactQueryClientProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ReactQueryClientProvider>
    </Suspense>

  );
}
